### ISSUE TITLE
A few comments on the code

### ISSUE THREAD

**Issue by mortenpi** [sostock/HalfIntegers.jl#2]
Sorry for the delay, but it also looks great to me! I really like the `half` function. In WignerSymols you have to do `HalfInteger(1, 2)`, but that gets old quickly. `half` seems like a perfect compromise between brevity and clarity.

I looked through the code and here a few observations / questions:

* I am wondering whether it is wise to allow the arithmetic to leave the half-integer space (I'm thinking about [multiplication](https://github.com/sostock/HalfIntegers.jl/blob/13ab1f4bfbdc67739327fbad123331f4f430ee35/src/HalfIntegers.jl#L59) and [division](https://github.com/sostock/HalfIntegers.jl/blob/13ab1f4bfbdc67739327fbad123331f4f430ee35/src/HalfIntegers.jl#L63) between HalfIntegers). I think it would be better to error in those situations, to make sure that you don't accidentally write code that should do everything with Halfs, but ends up using floats in the intermediate calculations.

* I find defining `lcm` and `gcd` for HalfIntegers a bit strange. Do you actually have a use case for these definitions?

* `Base.decompose` appears to be unexported and undocumented, so I am not sure if it is a good idea to rely on it. FWIW, I don't actually understand what it's even doing.

* I see you have some doctests. Do you think it would be worth setting up Documenter? 

* I don't think the `@eval`s are necessary [in the tests](https://github.com/sostock/HalfIntegers.jl/blob/13ab1f4bfbdc67739327fbad123331f4f430ee35/test/runtests.jl#L10-L29)?

The only thing I see that we have in WignerSymbols that we don't have here is an implementation of `Base.hash`. @jutho, would it be worth bringing it over?

We also define `one` and `zero` there, but those are not really necessary -- the general method from Base which falls back to the constructor works nicely.

**Comment by sostock** [comment]
Thanks for your comments, @mortenpi!

> I am wondering whether it is wise to allow the arithmetic to leave the half-integer space (I'm thinking about [multiplication](https://github.com/sostock/HalfIntegers.jl/blob/13ab1f4bfbdc67739327fbad123331f4f430ee35/src/HalfIntegers.jl#L59) and [division](https://github.com/sostock/HalfIntegers.jl/blob/13ab1f4bfbdc67739327fbad123331f4f430ee35/src/HalfIntegers.jl#L63) between HalfIntegers). I think it would be better to error in those situations, to make sure that you don't accidentally write code that should do everything with Halfs, but ends up using floats in the intermediate calculations.

I don’t think it would be wise to make standard arithmetic operations error on `HalfInteger`s. After all, you probably *do* want to use them in calculations, and division of two `Int`s does also not throw an error. But it should definitely be documented that multiplication and division result in floats (I am currently writing a more detailed documentation).

I also thought about using `Rational`s as the result for multiplication/division, but decided in favor of floats since `Rational`s are quite slow and not commonly used – how do you think about this?

> I find defining `lcm` and `gcd` for HalfIntegers a bit strange. Do you actually have a use case for these definitions?

In an earlier version of the code, I relied on [`Base.intersect(r::StepRange, s::StepRange)`](https://github.com/JuliaLang/julia/blob/95a52a5d6210ce07b54f1c8cb74eea88f0cd9eee/base/range.jl#L775-L818) for intersecting `StepRange`s of `HalfIntegers`, which requires `Base.lcm` and `Base.gcdx` to work. While these are not needed in the current implementation, I don’t see why they shouldn’t be defined. After all, gcd and lcm are well-defined for rational numbers (I actually wanted to make a PR to Julia to extend these function to `Rational`s as well, but haven’t found the time yet).

> `Base.decompose` appears to be unexported and undocumented, so I am not sure if it is a good idea to rely on it. FWIW, I don't actually understand what it's even doing.

`Base.decompose` is used by `Base.hash` for hashing real numbers (so that equivalent numbers of different types create the same hash). Therefore, I just extended `Base.decompose` instead of `Base.hash` to ensure that `hash(HalfInt(1/2)) == hash(1//2)`. While `Base.decompose` is indeed neither exported nor documented (there is a [comment in the code](https://github.com/JuliaLang/julia/blob/5d12d8696caf1d1ef1a86da9dab2cc2d43d3da09/base/hashing2.jl#L75-L94) explaining what it does), I don’t think the hashing algorithm is going to change in the near future. If it *does* change at some point, the test suite should catch that, since it [checks that hashing of `Half{T}` is consistent with other number types](https://github.com/sostock/HalfIntegers.jl/blob/13ab1f4bfbdc67739327fbad123331f4f430ee35/test/runtests.jl#L1744-L1749). I think it is worth extending `Base.decompose` instead of `Base.hash` simply because the implementation is much simpler.

> I see you have some doctests. Do you think it would be worth setting up Documenter?

I am currently writing more a detailed documentation (using Documenter) and plan to upload it before registering the package.

> I don't think the `@eval`s are necessary [in the tests](https://github.com/sostock/HalfIntegers.jl/blob/13ab1f4bfbdc67739327fbad123331f4f430ee35/test/runtests.jl#L10-L29)?

The `@eval`s are not necessary for the test suite to work, but they make the output (in the case of a failure) more useful: `@eval @test half($T, 5) === $T(7/2)` creates the output
```julia
Real: Test Failed at /home/sebastian/Development/HalfIntegers.jl/test/runtests.jl:226
  Expression: half(HalfUInt64, 5) === HalfUInt64(7 / 2)
```
while the output of `@test half(T, 5) === T(7/2)` does not list the actual types, but only `T`:
```julia
Real: Test Failed at /home/sebastian/Development/HalfIntegers.jl/test/runtests.jl:226
  Expression: half(T, 5) === T(7 / 2)
```
Since there are some tests where the distinction between different `T` is actually relevant (some operations on ranges currently behave correctly for *some* `Unsigned` types but not for others), I decided to use `@eval` even though it is unnecessary.

> We also define `one` and `zero` there, but those are not really necessary -- the general method from Base which falls back to the constructor works nicely.

Yeah, I tried not to implement any methods for which the fallback works (unless there are serious performance benefits). In the case of `one` and `zero`, I think the compiler should be able to optimize everything away (although I don’t think I actually checked this), so we probably wouldn’t benefit from a specialized implementation.

**Comment by Jutho** [comment]
FWIW, there does seem to be a small benefit to the custom `hash` function:
```
julia> using WignerSymbols, HalfIntegers, BenchmarkTools

julia> x = rand(-1000:1000, 10000);

julia> xfloat = x/2;

julia> xrat = x.//2;

julia> xhalf = half.(x);

julia> xwig = WignerSymbols.HalfInteger.(x, 2);

julia> y = hash.(x);

julia> @benchmark map!(hash, $y, $x)
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     26.254 μs (0.00% GC)
  median time:      27.258 μs (0.00% GC)
  mean time:        28.118 μs (0.00% GC)
  maximum time:     142.009 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1

julia> @benchmark map!(hash, $y, $xfloat)
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     36.866 μs (0.00% GC)
  median time:      38.995 μs (0.00% GC)
  mean time:        39.603 μs (0.00% GC)
  maximum time:     132.436 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1

julia> @benchmark map!(hash, $y, $xrat)
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     96.417 μs (0.00% GC)
  median time:      103.466 μs (0.00% GC)
  mean time:        106.371 μs (0.00% GC)
  maximum time:     300.126 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1

julia> @benchmark map!(hash, $y, $xhalf)
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     175.342 μs (0.00% GC)
  median time:      177.345 μs (0.00% GC)
  mean time:        184.564 μs (0.00% GC)
  maximum time:     602.389 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1

julia> @benchmark map!(hash, $y, $xwig)
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     93.089 μs (0.00% GC)
  median time:      94.630 μs (0.00% GC)
  mean time:        98.162 μs (0.00% GC)
  maximum time:     249.477 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1
```
So the custom `hash` performs as the one for rational, which however is still much slower than the one for `Float64`. The far better solution thus seems to be to just convert to `Float64`:
```
julia> @benchmark map!(z->hash(float(z)), $y, $xhalf)
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     43.134 μs (0.00% GC)
  median time:      44.856 μs (0.00% GC)
  mean time:        46.925 μs (0.00% GC)
  maximum time:     163.442 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1
```

**Comment by mortenpi** [comment]
> I don’t think it would be wise to make standard arithmetic operations error on `HalfInteger`s. After all, you probably _do_ want to use them in calculations, and division of two `Int`s does also not throw an error.

That's a good point, I forgot that there is a precedent for this with integer division. With that in mind, I think it's fine if the division of `Half`s is consistent with that and also results in a float.

But it still feels weird that multiplication would leave the space. And it does that only occasionally (i.e. not if one factor is an integer). So it means that you really have to mentally keep track of types in your expressions.

Rational would be slightly better since you would not lose precision at least, so it might be a good compromise. I still think an argument can be made that if you do arithmetic with half-integers, you don't want to end up with floating point numbers accidentally.

> After all, gcd and lcm are well-defined for rational numbers

Hmm..  it is not entirely clear what the definition is actually. LCM and GCD both reduce down to divisibility, and for me, the way to generalize is, [following Wikipedia, via integral domains](https://en.wikipedia.org/wiki/Divisor#Definition).

Based on that, currently from the code `lcm(3/2, 2) = 6`, but AFAICT it should be `3`, since `3/2 | 3` (`3/2 * 2 = 3`) and `2 | 3` (`2 * 3/2 = 3`).

As for rationals, all rational numbers are common multiples of any pair of rational numbers, since every rational (other than 0) divides every other rational? There is a related issue: JuliaLang/julia#27039

> `Base.decompose` is used by `Base.hash` for hashing real numbers (so that equivalent numbers of different types create the same hash).

I think it would be worth opening an issue to see if people are willing to make it official.

> The `@eval`s are not necessary for the test suite to work, but they make the output (in the case of a failure) more useful

Ah, yes, I didn't realize that. That's handy indeed.

**Comment by sostock** [comment]
Since we are now discussing three different topics in this thread, I have decided to open a separate issue for each one of them. I would suggest continuing discussion there:

* Hashing: #3
* Return type of multiplication/division: #4
* Extension of gcd/lcm: #5

I don’t think any of the other topics discussed initially require any further discussion, but if you think otherwise, feel free to open a separate issue for them.
